name: Build and Publish Docker Container
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and tag Docker image
      run: |
        docker build -t kruhlmann/tasmdocs:${{ github.sha }} .
        docker tag kruhlmann/tasmdocs:${{ github.sha }} kruhlmann/tasmdocs:latest
    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          kruhlmann/tasmdocs:${{ github.sha }}
          kruhlmann/tasmdocs:latest